### ISSUE TITLE
GH Pages Not Updating

### ISSUE THREAD

**Issue by tonymke** [Dran-Arcana/dredditisrecruiting.github.io#35]
For whatever reason, changes are not hitting the live site.

Usually the owner gets some variant of a "build failed" email when builds fail. Do you have any of these from github in your inbox, @Dran-Arcana ?

**Comment by Dran-Arcana** [comment]
I am not getting any "build failed" messages

**Comment by tonymke** [comment]
Weird. Maybe github doesn't like transferring pages between owners. I have opened a ticket with Github.

**Comment by tonymke** [comment]
Response from Github. **tl;dr add a "gh-pages" branch**. 

Did that, works now.

> Hi Tony,
> 
> Sorry about that!  Since the repository is no longer of the format "username.github.io", this is a Project Pages repository and the content should go in the gh-pages branch:
> 
> https://help.github.com/articles/user-organization-and-project-pages
> 
> If @Dran-Arcana renames the repository to dran-arcana.github.io and makes another push, then that should get things up and running.
> 
> Or if they want to keep the repository name, they'll need to push the site content to the gh-pages branch.
> 
> Hope these notes are helpful - if they still have trouble, feel free to have them get in touch with us directly and we'll investigate with them further.
> 
> Thanks,
> Robert
> 
> > I transferred ownership of a pages repo, https://github.com/Dran-Arcana/dredditisrecruiting.github.io, from myself to user Dran-Arcana. Since doing that, updates to the repo build successfully, (no "build error" emails, etc), but do not reflect on the rendered site.
> > 
> > Is there something we're missing as far as triggering new builds? https://github.com/Dran-Arcana/dredditisrecruiting.github.io
